version: '3'

services:
  db:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'


  app:
    depends_on:
      - 'db'
      - 'redis'
    build: .
    command: bash start.sh
    ports:
      - '3000:3000'
    volumes:
      - '.:/searchjob'
      - 'box:/box'
    stdin_open: true
    tty: true

  box:
    image: busybox
    volumes:
      - box:/box

  mailcatcher:
    image: tophfr/mailcatcher
    ports:
      - 1025:25
      - 1080:80

volumes:
  redis:
  postgres:
  box: